version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
  back-tier:

services:
 
  pushgateway:
    image: prom/pushgateway
    build:
      context: ./
      dockerfile: Dockerfile.pushgateway
    ports:
      - 9091:9091
    networks:
      - back-tier

  prometheus:
    image: prom/prometheus
    #build:
    #  context: ./
    #  dockerfile: Dockerfile.prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    devices:
      - /dev/nvidia0
    links:
      - pushgateway
    depends_on:
      - pushgateway
    networks:
      - back-tier
    restart: always
    deploy:
      #placement:
        #constraints:
        #  - node.hostname == moby

  grafana:
    image: grafana/grafana
    #build:
     ## context: ./
    #  dockerfile: Dockerfile.grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - config.monitoring
    networks:
      - back-tier
      - front-tier
