
FROM ubuntu:16.04
RUN apt-get update -y && apt-get install -y 
RUN git clone https://github.com/Markonick/gpumetrics.git
WORKDIR gpumetrics
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
RUN dpkg -i cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
RUN apt-get update -y
RUN apt-get install -y cuda
